version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app'
    restart: always
    ports:
      - 3002:3002
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npx prisma generate && npx prisma migrate deploy && npm start"
    user: "1000:1000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14
    container_name: postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    name: local
